n = input('Digite algo:')

print('o tipo desse valor é:', type(n))
print("é uma letra?", n.isalpha())
print('é um numero?', n.isnumeric())
print('é um mumero ou uma letra?', n.isalnum())
print('é um?', n.isascii())
print('esta em minusculo?', n.islower())
print('esta em maiusculo?', n.isupper())
print('é um titulo?', n.istitle())
print(n.isspace())
print(n.isdigit())
print(n.isdecimal())
print(n.isprintable())
print(n.isidentifier())
